# Generated by Django 6.0.5 on 2026-05-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_angular_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='angular',
            name='answer2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='contentStatus',
            field=models.CharField(default='active', max_length=50),
        ),
        migrations.AddField(
            model_name='angular',
            name='image2Url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='image3Url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='imageUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='serial',
            field=models.CharField(default='01', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='visible',
            field=models.BooleanField(db_index=True, default=True, help_text='Indicates whether the content is visible to users.', verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='angular',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='angular',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='angular',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='angular',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
