# Generated by Django 6.0.5 on 2026-05-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_angular_answer2_angular_contentstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angular',
            old_name='image2Url',
            new_name='image2_url',
        ),
        migrations.RenameField(
            model_name='angular',
            old_name='image3Url',
            new_name='image3_url',
        ),
        migrations.RenameField(
            model_name='angular',
            old_name='imageUrl',
            new_name='image_url',
        ),
        migrations.RemoveField(
            model_name='angular',
            name='contentStatus',
        ),
        migrations.AddField(
            model_name='angular',
            name='angular_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='angular',
            name='content_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='angular',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
