# Generated by Django 6.0.5 on 2026-05-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_image2url_angular_image2_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='angular',
            old_name='serial',
            new_name='serial_number',
        ),
        migrations.AlterField(
            model_name='angular',
            name='topic',
            field=models.CharField(default='general', max_length=100),
        ),
    ]
